#!/bin/sh

# After each commit on master (GitHub), it will switch to the Heroku branch and cherry-pick that commit into it. Then, switch back to master.
# This makes the committing flow seamless so all you have to do is push (which is safer done manually than with a hook)

ERR='[ERR] '
SUCCESS='[SUCCESS] '
WARN='[WARN] '
space="\n\n\n"

branch=`git branch | grep \* | cut -d ' ' -f2`
heroku="heroku" # private branch
github="master" # public branch

if [ "$branch" = $github ]
then
    echo $space
    
    echo "${WARN}Executing post-commit script (cherry-pick)..."
    commitID=`git rev-parse HEAD`
    
    if git checkout $heroku; then
        if git cherry-pick $commitID; then
            echo "${SUCCESS}Cherry picked $commitID into $heroku branch $space"
            if ! git checkout $github; then
                echo "${ERR}Couldn't checkout to $github $space"
                exit 1
            fi
        else
            echo "${ERR}Failed to cherry pick $commitID into $heroku branch. Do it manually $space"
            exit 1
        fi
    else
        echo "${ERR}Couldn't checkout to $heroku $space"
        exit 1
    fi
    
fi

exit 0
